### ISSUE TITLE
What's the relationship between tidb-dev-guide and tidb-source-code-reading?

### ISSUE THREAD

**Issue by xxchan** [pingcap/tidb-dev-guide#100]
There exist a series called [tidb-source-code-reading](https://github.com/pingcap/blog-cn/blob/master/tidb-source-code-reading-1.md). Is `tidb-dev-guide` just a new version of `tidb-source-code-reading`? Do they have different writing goals?

Similarly for [tikv-dev-guide](https://github.com/tisonkun/tikv-dev-guide) and [deep-dive-tikv](https://github.com/tikv/website/tree/master/content/deep-dive).

**Comment by tisonkun** [comment]
Thanks for asking this question.

### TiDB Dev Guide

A bit history: there was an offline discussion among TiDB developers, @zz-jason @dragonly and I, on porting source code reading series to GitHub materials so that we can continuous update it. Although the original blogs are also hosted on GitHub, they are published articles that may not evolute.

So, you can regard Understanding TiDB chapter of TiDB Dev Guide as an evolution of and continuously evolving source code reading series.

Get Started and Contribute to TiDB chapter basically collect materials from [pingcap/community](https://github.com/pingcap/community), [pingcap/tidb-map](https://github.com/pingcap/tidb-map), and other best practice in our community, to help newcomer to get start their journey in TiDB community, and summarize typical participant path.

Project Management chapter is aimed at showing how we build a software, its development cycle, its release, its issues management, pr management, and so on.

### TiKV Dev Guide

The same with the other three chapter, for Understanding TiKV, I'd like to quote @andylockandy who writes the table of content and said to me "This is from TiKV Deep Dive and let's make it great again."

I've ever asked for just polish TiKV Deep Dive but contributors tend to write a new one. I'll ensure it won't be a new uncompleted or outdated one and also clean up (redirect) legacy stuff.

**Comment by xxchan** [comment]
So dev-guide is superset of source code reading. Exciting!

> I'll ensure it won't be a new uncompleted or outdated one and also clean up (redirect) legacy stuff.

Thank you for your effort! And I think redirection and your explanations here are needed to avoid confusion.

**Comment by tisonkun** [comment]
Redirection from where? If you mean Deep Dive, I think we will update the page later; if you mean source code reading series, I don't have a strong feeling on it. Maybe you can just file an issue or pull request on https://github.com/pingcap/blog repo and https://github.com/pingcap/blog-cn repo.

**Comment by tisonkun** [comment]
closed as answered.

**Comment by tisonkun** [comment]
Also I mention this issue on [This Week on TiDB 20210822](https://zhuanlan.zhihu.com/p/402451398)
