### ISSUE TITLE
Completing setup vscode for getting start

### ISSUE THREAD

**Issue by oops-lgtm** [pingcap/tidb-dev-guide#47]
any plan on completing [vscode](https://zz-jason.gitbook.io/tidb-dev-guide/get-started/setup-an-ide#vs-code) of Chapter `Setup an IDE` ?

**Comment by tisonkun** [comment]
@oops-lgtm thanks for your report! Currently there is no volunteer who works for this section. If you are familiar with setting up dev env for TiDB with VS Code, it's encouraged that just sending a pull request.

If you are seeking for guide, I'll leave it as help wanted for now.

**Comment by feitian124** [comment]
interesting... i use vscode often but not for go.
I know there is a incubator project [tide](https://github.com/tidb-incubator/tide ) which is a Visual Studio Code extension that makes developing TiDB a breeze. 
the authors must be experts on this part, if they can created a guide on this(and maybe with tide :smiley: ), it is amazing.

**Comment by sunxiaoguang** [comment]
> interesting... i use vscode often but not for go.
> I know there is a incubator project [tide](https://github.com/tidb-incubator/tide) which is a Visual Studio Code extension that makes developing TiDB a breeze.
> the authors must be experts on this part, if they can created a guide on this(and maybe with tide 😃 ), it is amazing.

The amazing part of open source community is that everybody can be a contributor and the contribution benefits everybody including themselves. Thanks @feitian124 for suggesting TiDE, and your are very welcome to contribute this particular section as well.

**Comment by feitian124** [comment]
i made some research and find go dev on vscode is quite convinient because of official [Go extension for VS Code](https://github.com/golang/vscode-go).

some operation such as `run unit-test` lacks ui support compared with `goland`, but as vscode [Testing API finalized ](https://code.visualstudio.com/updates/v1_59#_testing-apis) in release `1.59`, it will catch up soon, see progress [here](https://github.com/golang/vscode-go/pull/1590).

maybe i can finish this part if no other volunteer

**Comment by mjonss** [comment]
Was not this done in https://github.com/pingcap/tidb-dev-guide/pull/107 ?

**Comment by tisonkun** [comment]
closed as resolved.
